[gearman]
server=scheduler

[gearman_server]
start=true

[zookeeper]
hosts=zookeeper:2181

[database]
dburi=mysql+pymysql://zuul:zuul_pass@mysql/zuul

[scheduler]
tenant_config=/etc/zuul/main.yaml

[web]
listen_address=0.0.0.0
port=9000
root=http://YOUR_STATIC_IP:9000

[executor]
private_key_file=/var/lib/zuul/.ssh/id_rsa

[connection github]
driver=github
server=github.com
app_id=YOUR_GITHUB_APP_ID
app_key=/etc/zuul/github-app.pem
webhook_token=YOUR_WEBHOOK_SECRET
