[zookeeper]
hosts=zookeeper:2281
tls_cert=/etc/zuul/certs/clientcert.pem
tls_key=/etc/zuul/certs/clientkey.pem
tls_ca=/etc/zuul/certs/cacert.pem

[keystore]
password=zuul_keystore_pass

[database]
dburi=mysql+pymysql://zuul:zuul_pass@mysql/zuul

[scheduler]
tenant_config=/etc/zuul/main.yaml

[web]
listen_address=0.0.0.0
port=9000
root=http://35.239.241.176:9000

[executor]
private_key_file=/var/lib/zuul/.ssh/id_rsa

[connection github]
driver=github
server=github.com
app_id=3084515
app_key=/etc/zuul/github-app.pem
webhook_token=f0236baaa987218dece53b9de40bfd4f1c8e0199
